import Foundation

/// Resource categories emitted by the photo import adapter.
public enum BatchImageImportResourceKind: String, Codable, Equatable, Sendable {
    /// A standard photo resource.
    case photo
    /// A full-size original photo resource.
    case fullSizePhoto = "full_size_photo"
    /// An alternate photo representation.
    case alternatePhoto = "alternate_photo"
    /// A paired live-photo video resource.
    case pairedVideo = "paired_video"
    /// A standard video resource.
    case video
    /// An audio-only resource.
    case audio
    /// A full-size original video resource.
    case fullSizeVideo = "full_size_video"
    /// Adjustment payload data generated by Photos edits.
    case adjustmentData = "adjustment_data"
    /// A full-size paired video resource.
    case fullSizePairedVideo = "full_size_paired_video"
    /// A paired-video adjustment base resource.
    case adjustmentBasePairedVideo = "adjustment_base_paired_video"
    /// Any resource kind not mapped to a known photo-library case.
    case other
}
